version: "3.8"

services:
  localstack:
    image: localstack/localstack:3.0
    ports:
      - "4566:4566"
    environment:
      SERVICES: s3,ec2,iam,rds,kms,cloudtrail,cloudformation
      DEFAULT_REGION: eu-west-2
      AWS_DEFAULT_REGION: eu-west-2
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4566/_localstack/health"]
      interval: 10s
      timeout: 5s
      retries: 5
