from pathlib import Path

import click
import yaml

from driftfinder.core.config import CONFIG_FILE_NAME, DriftFinderConfig
from driftfinder.models.enums import FailOn, IaCTool, OutputFormat


@click.command("init")
@click.option(
    "--config",
    "config_path",
    default=CONFIG_FILE_NAME,
    show_default=True,
    help="Path to write the config file.",
)
@click.option("--force", is_flag=True, default=False, help="Overwrite an existing config file.")
def init_command(config_path: str, force: bool) -> None:
    """Interactive wizard that creates .driftfinder.yml."""
    path = Path(config_path)

    if path.exists() and not force:
        click.secho(
            f"Config file '{config_path}' already exists. " "Use --force to overwrite.",
            fg="yellow",
        )
        raise SystemExit(0)

    click.secho("DriftFinder setup wizard", bold=True)
    click.echo("Press Enter to accept defaults shown in brackets.\n")

    tool_choice = click.prompt(
        "IaC tool",
        type=click.Choice([t.value for t in IaCTool]),
        default=IaCTool.TERRAFORM.value,
    )
    tool = IaCTool(tool_choice)

    if tool == IaCTool.TERRAFORM:
        state_file = click.prompt(
            "Terraform state file (local path or s3://...)",
            default="terraform.tfstate",
        )
        stack_name = None
        pulumi_stack = None
    elif tool == IaCTool.CLOUDFORMATION:
        state_file = None
        stack_name = click.prompt("CloudFormation stack name")
        pulumi_stack = None
    else:
        state_file = None
        stack_name = None
        pulumi_stack = click.prompt("Pulumi stack export JSON path")

    aws_region = click.prompt("AWS region", default="eu-west-2")
    aws_profile = click.prompt("AWS profile (leave blank for default credential chain)", default="")
    fail_on = click.prompt(
        "Fail on severity",
        type=click.Choice([f.value for f in FailOn]),
        default=FailOn.CRITICAL.value,
    )
    output_format = click.prompt(
        "Output format",
        type=click.Choice([f.value for f in OutputFormat]),
        default=OutputFormat.BOTH.value,
    )

    data: dict = {
        "iac_tool": tool.value,
        "aws_region": aws_region,
        "fail_on": fail_on,
        "output_format": output_format,
    }
    if state_file:
        data["state_file"] = state_file
    if stack_name:
        data["stack_name"] = stack_name
    if pulumi_stack:
        data["pulumi_stack"] = pulumi_stack
    if aws_profile:
        data["aws_profile"] = aws_profile

    # Validate the config before writing
    try:
        DriftFinderConfig(**data)
    except Exception as exc:
        click.secho(f"Config validation failed: {exc}", fg="red", err=True)
        raise SystemExit(2) from None

    path.write_text(
        "# Generated by: driftfinder init\n" + yaml.dump(data, default_flow_style=False),
        encoding="utf-8",
    )
    click.secho(f"\nConfig written to {config_path}", fg="green")
    click.echo("Run 'driftfinder scan' to start detecting drift.")
